server:
  port: 8084
  
spring:
  application:
    name: micro-purchase
  data:
    mongodb:
      uri: mongodb://localhost:12500/purchase
      #uri: mongodb://bootcamb-db:uMamqpjJ0iG4gPsLyJXEAaqfW8685r2SEWaIYmBvtH9aYigkhka31qHcEazga17iyFoWmkEHbZNQRpQAUdTnbg==@bootcamb-db.mongo.cosmos.azure.com:10255/purchase?ssl=true&retrywrites=false&replicaSet=globaldb&maxIdleTimeMS=120000&appName=@bootcamb-db@
  kafka:
    #bootstrap-servers: 52.160.125.8:9092
     bootstrap-servers: localhost:9092

logging:
  level:
    root: info

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8888/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: false
    hostname: 192.168.1.136

gateway:
  baseUrl: http://localhost:8080
