server:
  port: 8095
  
spring:
  application:
    name: micro-withdrawal
  data:
    mongodb:
      uri: mongodb://localhost:27017/withdrawal
  kafka:
    bootstrap-servers: localhost:29092

kafka:
  server:
    hostname: localhost
    port: 29092

eureka:
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:8099/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true
    hostname: localhost
