server:
  port: 8082
  
spring:
  application:
    name: micro-customer
  data:
    mongodb:
      uri: mongodb://localhost:12500/customer
#      uri: mongodb://bootcamb-db:uMamqpjJ0iG4gPsLyJXEAaqfW8685r2SEWaIYmBvtH9aYigkhka31qHcEazga17iyFoWmkEHbZNQRpQAUdTnbg==@bootcamb-db.mongo.cosmos.azure.com:10255/customer?ssl=true&retrywrites=false&replicaSet=globaldb&maxIdleTimeMS=120000&appName=@bootcamb-db@      
  kafka:
     #bootstrap-servers: 52.160.125.8:9092
     bootstrap-servers: localhost:9092
    
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8888/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true
    hostname: 192.168.1.136
